version: '3'

services:
  dynamodb:
    image: amazon/dynamodb-local:1.13.5
    networks:
      - lambdaid
    ports:
      - "8027:8000"
    volumes:
      - /data

  minio:
    image: minio/minio:RELEASE.2020-10-12T21-53-21Z
    networks:
      - lambdaid
    ports:
      - "8028:9000"
    volumes:
      - /data
    environment:
      # This matches what the sam CLI uses.
      - MINIO_ACCESS_KEY=defaultkey
      - MINIO_SECRET_KEY=defaultsecret
    command: "server /data"

networks:
  lambdaid:
    name: lambdaid
