version: '3'

services:
  dynamodb:
    image: amazon/dynamodb-local:1.16.0
    ports:
      - "8027:8000"
    volumes:
      - /data

  minio:
    image: minio/minio:RELEASE.2021-10-08T23-58-24Z
    ports:
      - "8028:9000"
    volumes:
      - /data
    environment:
      # This matches what the sam CLI uses.
      - MINIO_ACCESS_KEY=defaultkey
      - MINIO_SECRET_KEY=defaultsecret
    command: "server /data"
