AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Description: >
  lambdaid

Parameters:
  DomainName:
    Type: String
    Description: Domain name to serve this app as

  HostedZoneID:
    Type: String
    Description: Hosted zone the domain name lives in

  CertificateARN:
    Type: String
    Description: ARN of the certificate to use for serving

# More info about Globals: https://github.com/awslabs/serverless-application-model/blob/master/docs/globals.rst
Globals:
  Function:
    Timeout: 5

Resources:
  # Info on implicitly generated resources: https://github.com/awslabs/serverless-application-model/blob/master/docs/internals/generated_resources.rst#api
  IDPFunction:
    Type: AWS::Serverless::Function # More info about Function Resource: https://github.com/awslabs/serverless-application-model/blob/master/versions/2016-10-31.md#awsserverlessfunction
    Properties:
      CodeUri: idp/
      Handler: idp
      Runtime: go1.x
      Tracing: Active # https://docs.aws.amazon.com/lambda/latest/dg/lambda-x-ray.html
      Events:
        CatchAll:
          Type: Api # More info about API Event Source: https://github.com/awslabs/serverless-application-model/blob/master/versions/2016-10-31.md#api
          Properties:
            # TODO - do we want to be explicit, or do we just want to proxy it all?
            Path: /hello
            Method: GET
            RestApiId: !Ref ApiGateway
      Environment: # More info about Env Vars: https://github.com/awslabs/serverless-application-model/blob/master/versions/2016-10-31.md#environment-object
        Variables:
          PARAM1: VALUE

  ApiGateway:
    Type: AWS::Serverless::Api
    Properties:
      Name: !Sub ${AWS::StackName}-gateway
      StageName: Prod
      EndpointConfiguration: EDGE
      Domain:
        DomainName: !Ref DomainName
        CertificateArn: !Ref CertificateARN
        EndpointConfiguration: EDGE
        Route53:
          HostedZoneId: !Ref HostedZoneID

Outputs:
  IDPFunction:
    Description: "IDP Lambda Function ARN"
    Value: !GetAtt IDPFunction.Arn
  IDPFunctionIamRole:
    Description: "Implicit IAM Role created for IDP World function"
    Value: !GetAtt IDPFunctionRole.Arn
