name: Lambda Publish

on:
  push:
    branches: [ '*' ]
  pull_request:
    branches: [ main ]

jobs:

  release:
    runs-on: ubuntu-latest
    env:
      # https://github.com/aws/aws-cli/issues/5262#issuecomment-705832151
      AWS_EC2_METADATA_DISABLED: "true"
    steps:
    - uses: actions/checkout@v2

    - name: Set up Go
      uses: actions/setup-go@v2
      with:
        go-version: 1.17

    - name: Pre-build
      run: go build ./...

    - name: Debug
      env:
        AWS_REGION: ${{ secrets.AWS_REGION }}
        AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
        AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
      run: aws sts get-caller-identity

    - name: Run release script
      env:
        AWS_REGION: ${{ secrets.AWS_REGION }}
        AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
        AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
      run: ./hack/release_s3.sh
